# Generated by Django 6.0 on 2026-03-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('spouse_name', models.CharField(blank=True, max_length=150, verbose_name='Tên vợ/chồng')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='other', max_length=10, verbose_name='Giới tính')),
                ('generation', models.PositiveIntegerField(default=1, verbose_name='Đời thứ')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('death_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm mất')),
                ('hometown', models.CharField(blank=True, max_length=150, verbose_name='Quê quán')),
                ('biography', models.TextField(blank=True, verbose_name='Tiểu sử ngắn')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Hiển thị nổi bật ở trang chủ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='genealogy.familymember', verbose_name='Thành viên đời trước')),
            ],
            options={
                'verbose_name': 'Thành viên gia phả',
                'verbose_name_plural': 'Thành viên gia phả',
                'ordering': ['generation', 'full_name'],
            },
        ),
    ]
