# Generated by Django 6.0 on 2026-03-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tieu de')),
                ('content', models.TextField(verbose_name='Noi dung')),
                ('author', models.CharField(max_length=120, verbose_name='Tac gia')),
                ('image_url', models.URLField(blank=True, verbose_name='Hinh anh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bai viet',
                'verbose_name_plural': 'Bai viet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['generation', 'full_name'], 'verbose_name': 'Thanh vien gia pha', 'verbose_name_plural': 'Thanh vien gia pha'},
        ),
        migrations.AlterField(
            model_name='familymember',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Tieu su ngan'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nam sinh'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nam mat'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Ho va ten'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nu'), ('other', 'Khac')], default='other', max_length=10, verbose_name='Gioi tinh'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='generation',
            field=models.PositiveIntegerField(default=1, verbose_name='Doi thu'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='hometown',
            field=models.CharField(blank=True, max_length=150, verbose_name='Que quan'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Noi bat o trang gioi thieu'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='genealogy.familymember', verbose_name='Thanh vien doi truoc'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ten vo chong'),
        ),
    ]
