# Generated by Django 6.0 on 2026-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_article_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, upload_to='articles/', verbose_name='Tai anh len'),
        ),
    ]
