# Generated by Django 6.0 on 2026-04-21 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bài viết', 'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['generation', 'full_name'], 'verbose_name': 'Thành viên gia phả', 'verbose_name_plural': 'Thành viên gia phả'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=120, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, upload_to='articles/', verbose_name='Tải ảnh lên'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Tiểu sử ngắn'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm mất'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='other', max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='generation',
            field=models.PositiveIntegerField(default=1, verbose_name='Đời thứ'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='hometown',
            field=models.CharField(blank=True, max_length=150, verbose_name='Quê quán'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Nổi bật ở trang giới thiệu'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='genealogy.familymember', verbose_name='Thành viên đời trước'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tên vợ/chồng'),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=120, verbose_name='Tên người bình luận')),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='genealogy.article', verbose_name='Bài viết')),
            ],
            options={
                'verbose_name': 'Bình luận bài viết',
                'verbose_name_plural': 'Bình luận bài viết',
                'ordering': ['created_at'],
            },
        ),
    ]
