# Generated by Django 6.0 on 2026-04-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_alter_article_options_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='Công danh'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='education',
            field=models.CharField(blank=True, max_length=150, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tên cha'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tên mẹ'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nghề nghiệp'),
        ),
    ]
