# Generated by Django 6.0 on 2026-04-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0005_familymember_achievements_familymember_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bai vi?t', 'verbose_name_plural': 'Bai vi?t'},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Binh lu?n bai vi?t', 'verbose_name_plural': 'Binh lu?n bai vi?t'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['branch', 'generation', 'full_name'], 'verbose_name': 'Thanh vien gia ph?', 'verbose_name_plural': 'Thanh vien gia ph?'},
        ),
        migrations.AddField(
            model_name='familymember',
            name='branch',
            field=models.CharField(choices=[('canh_truong', 'Canh tr??ng'), ('canh_2', 'Canh 2'), ('canh_3', 'Canh 3'), ('canh_4', 'Canh 4'), ('canh_5', 'Canh 5')], default='canh_truong', max_length=20, verbose_name='Canh h?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=120, verbose_name='Tac gi?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='N?i dung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, upload_to='articles/', verbose_name='T?i ?nh len'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Hinh ?nh'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tieu ??'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='genealogy.article', verbose_name='Bai vi?t'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='commenter_name',
            field=models.CharField(max_length=120, verbose_name='Ten ng??i binh lu?n'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=models.TextField(verbose_name='N?i dung binh lu?n'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='Cong danh'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Ti?u s? ng?n'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N?m sinh'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N?m m?t'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='education',
            field=models.CharField(blank=True, max_length=150, verbose_name='Trinh ??'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ten cha'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='H? va ten'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'N?'), ('other', 'Khac')], default='other', max_length=10, verbose_name='Gi?i tinh'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='generation',
            field=models.PositiveIntegerField(default=1, verbose_name='??i th?'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='hometown',
            field=models.CharField(blank=True, max_length=150, verbose_name='Que quan'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='N?i b?t ? trang gi?i thi?u'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ten m?'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chu'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ngh? nghi?p'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='genealogy.familymember', verbose_name='Thanh vien ??i tr??c'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ten v?/ch?ng'),
        ),
    ]
